### ISSUE TITLE
Adding a Delete Button

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-assignment-5#1]
@thomasjbradley

Trying to figure out how to create a button across from the li's that are created when form is submitted

$form.on('submit',function (eventObject) {
     eventObject.preventDefault();

```
 var $listItem = $('<li>');
 $listItem.html($input.val())

 $addToList.append($listItem).addClass($priority.val());

 $input.val('');

var $priority = $('[name=priority]:checked');
```

 });

**Comment by thomasjbradley** [comment]
On this line of JS we're creating a new `li`:
https://github.com/valeriebordeleau/dsn1676-assignment-5/blob/gh-pages/js/main.js#L9
So, we have to do something similar but create a new `button` too.

**Comment by valeriebordeleau** [comment]
I tried 
`var $listItem = $('<li>', '<button>');
     $listItem.html($input.val())`
but it creates a blank 
button instead of text

**Comment by thomasjbradley** [comment]
Yeah, because the code won't let you make two elements at once.
You'll need a whole new variable to make a new button.

**Comment by valeriebordeleau** [comment]
currently i have it like this

   $form.on('submit',function (eventObject) {
    eventObject.preventDefault();

```
var $listItem = $('<li>');
$listItem.html($input.val())

$addToList.append($listItem).addClass($priority.val());

var $button = $('<button class="delete">X</button>');
$listItem.html($input.val())

$button.on('click', function () {
$li.remove('li');
});
```

 });

but the button still isn't appearing

**Comment by thomasjbradley** [comment]
The button needs to be appended to the li.

**Comment by valeriebordeleau** [comment]
$form.on('submit',function (eventObject) {
    eventObject.preventDefault();

```
var $listItem = $('<li>');
$listItem.html($input.val())
var $priority = $('[name=priority]:checked');

$addToList.append($listItem).addClass($priority.val())
$button.append($listItem)

var $button = $('<button class="delete">X</button>');
$listItem.html($input.val())
```

 });

I have it set like this but it's still not working. Is it an ordering issue?

**Comment by thomasjbradley** [comment]
Partial ordering issue, partial backwards code issue:

``` js
$button.append($listItem).addClass($priority.val())
```

This line needs to come after the `var $button` line.

---

And, this line is backwards:

``` js
$button.append($listItem)
```

It says, take the `$listItem` and append it onto the `$button`.

**Comment by valeriebordeleau** [comment]
That solves the button appearing however it applies the greyed out css instead of deleting the line now.

**Comment by valeriebordeleau** [comment]
Issue solved
