### ISSUE TITLE
Trying to get to get list items to change colour according to priority

### ISSUE THREAD

**Issue by valeriebordeleau** [valeriebordeleau/dsn1676-assignment-5#2]
@thomasjbradley
Trying to get to get list items to change colour according to priority. Can't link CSS to values associated with radio button.

```
<form class="pad-top">
<feildset class="island">
<input type="radio" id="low-priority" name="priority" value="1">
<label for="low-priority">Low Priority</label>    
<input type="radio" id="high-priority" name="priority" value="2">
<label for="high-priority">High Priority</label> 
</feildset>

<label for="add-item">What do you need to do?</label>
<input id="add-item">
<button class="button" type="submit">Add Item</button>
</form>
```

$form.on('submit',function (eventObject) {
     eventObject.preventDefault();

```
 var $listItem = $('<li>');
 $listItem.html($input.val())

 $addToList.append($listItem).addClass($priority.val());

 $input.val('');

var $priority = $('[name=priority]:checked');
```

 });

**Comment by thomasjbradley** [comment]
I think it's a matter of code order.

On this line we're trying to use the priority:
https://github.com/valeriebordeleau/dsn1676-assignment-5/blob/gh-pages/js/main.js#L12

But it doesn't actually exist until further down the code, on this line:
https://github.com/valeriebordeleau/dsn1676-assignment-5/blob/gh-pages/js/main.js#L16

**Comment by valeriebordeleau** [comment]
that solved the issue of getting the code to apply to li's however now whatever priority you choose is applied to all Li's after the first is chosen

**Comment by thomasjbradley** [comment]
The variable statement is just too high up in the code. I still needs to be inside the function.
